[package]
name = "maximumadhd/roblox-boilerplate"
description = ""
version = "1.0.0"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"

[dependencies]
Red = "red-blox/red@2.3.2"
React = "jsdotlua/react@17.2.1"
Trove = "sleitnick/trove@0.5.0"
Future = "red-blox/future@1.0.1"
Ripple = "littensy/ripple@0.9.0"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
